actions : 
  copy:
    mount:
      remote:
        directory: "c:/src_files/"
    git:
      remote:
        directory: "git...."
  install:
  documentation:
    git:
      remote:
        directory: "git...."